# Week 6 Project

## Gretchen Greene

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->
```{r cahc = TRUE}
data_site <- 
  "http://tiny.cc/dcf/2014-Q4-Trips-History-Data-Small.rds" 
Trips <- readRDS(gzcon(url(data_site)))
```
1.
```{r}
Trips %>%
  ggplot(aes(x = sdate)) + 
  geom_density(bw=100000)
```
2. 
```{r}
Trips %>% 
  mutate(time_of_day = 
       lubridate::hour(sdate) + 
         lubridate::minute(sdate) / 60) %>%
  ggplot(aes(x= time_of_day)) + 
  geom_density()
```
3. 
```{r}
Trips %>% 
  mutate(day_of_week = 
       lubridate::wday(sdate))%>%
  mutate(time_of_day = 
       lubridate::hour(sdate) + 
         lubridate::minute(sdate) / 60) %>%
  ggplot(aes(x= time_of_day)) + 
  geom_density() +
    facet_wrap(~day_of_week)
```
4.
```{r}
Trips %>% 
  mutate(day_of_week = 
       lubridate::wday(sdate))%>%
  mutate(time_of_day = 
       lubridate::hour(sdate) + 
         lubridate::minute(sdate) / 60) %>%
  ggplot(aes(x= time_of_day)) + 
  geom_density(aes(fill=client),alpha=0.5) +
    facet_wrap(~day_of_week)  
```
5. 
```{r}
Trips %>% 
  mutate(day_of_week = 
       lubridate::wday(sdate))%>%
  mutate(time_of_day = 
       lubridate::hour(sdate) + 
         lubridate::minute(sdate) / 60) %>%
  ggplot(aes(x= time_of_day)) + 
  geom_density(aes(fill=client),alpha=0.5, position = position_stack()) +
    facet_wrap(~day_of_week)  
```
6. 
```{r}
Trips %>% 
  mutate(wday = ifelse(lubridate::wday(sdate) %in% c(1,7), "weekend", "weekday")) %>%
  mutate(time_of_day = 
       lubridate::hour(sdate) + 
         lubridate::minute(sdate) / 60) %>%
  ggplot(aes(x= time_of_day)) + 
  geom_density(aes(fill=client),alpha=0.5, position = position_stack()) +
    facet_wrap(~wday)
```
